import { Dashboard } from "@/components/Dashboard/dashboard";
import { Header } from "@/components/UI/Header/header-main/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../globals.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Dashboard>{children}</Dashboard>
      </body>
    </html>
  );
}
