import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import style from "./search.module.scss";
import "../../globals.css";
import { PanelTarget } from "@/components/UI/Target/PanelTarget";
import { SearchComponent } from "@/components/SearchInput/SearchInput";

const inter = Oswald({
  subsets: ["latin"],
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LayoutSearch({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${inter.className} ${style.Layout}`}>
      <SearchComponent />
      {children}
    </div>
  );
}
